apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-credentials
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysql.rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-credentials
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.secrets.keycloak.user | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.keycloak.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.keycloak.rootPassword | quote }}
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloak.admin | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloak.adminPassword | quote }}
