global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'accounts'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets:
          - 'accounts:8080'
  - job_name: 'cards'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets:
          - 'cards:8081'
  - job_name: 'loans'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets:
          - 'loans:8082'
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets:
          - 'config-server:8071'
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets:
          - 'discovery-service:8070'
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets:
          - 'gateway-service:8072'
