apiVersion: v2
name: microservices
description: A Helm chart for Spring Boot Microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

# Dependencies
dependencies:
  - name: mysql
    version: "13.0.2"
    repository: "https://charts.bitnami.com/bitnami"
    alias: mysql-accounts
    condition: mysql-accounts.enabled
  - name: mysql
    version: "13.0.2"
    repository: "https://charts.bitnami.com/bitnami"
    alias: mysql-cards
    condition: mysql-cards.enabled
  - name: mysql
    version: "13.0.2"
    repository: "https://charts.bitnami.com/bitnami"
    alias: mysql-loans
    condition: mysql-loans.enabled
  - name: rabbitmq
    version: "16.0.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: redis
    version: "21.2.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: minio
    version: "17.0.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
  - name: keycloak
    version: "24.7.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled
  - name: loki-stack
    version: "2.10.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.enabled
