apiVersion: v1
kind: Service
metadata:
  name: mysql-accounts
spec:
  selector:
    app: mysql-accounts
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-accounts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-accounts
spec:
  selector:
    matchLabels:
      app: mysql-accounts
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-accounts
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-accounts
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: accountsdb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-accounts-persistent-storage
          mountPath: /var/lib/mysql
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$(MYSQL_ROOT_PASSWORD)"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$(MYSQL_ROOT_PASSWORD)"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mysql-accounts-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-accounts-pvc