apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 8071
      targetPort: 8071
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: nazjara/configserver:1.0.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8071
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: OTEL_SERVICE_NAME
          value: configserver
        volumeMounts:
        - name: configserver-persistent-storage
          mountPath: /app/data
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8071
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8071
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: configserver-persistent-storage
        persistentVolumeClaim:
          claimName: configserver-pvc
