apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: nazjara/accounts:1.0.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_CONFIG_SERVER_URI
          value: http://config-server:8071
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: DB_URL
          value: jdbc:mysql://mysql-accounts:3306/accountsdb
        - name: SPRING_EUREKA_SERVER_URI
          value: http://discovery-service:8070
        - name: OTEL_SERVICE_NAME
          value: accounts
        volumeMounts:
        - name: accounts-persistent-storage
          mountPath: /app/data
      volumes:
      - name: accounts-persistent-storage
        persistentVolumeClaim:
          claimName: accounts-pvc
