apiVersion: v1
kind: Service
metadata:
  name: loans
spec:
  selector:
    app: loans
  ports:
    - port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loans-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans
spec:
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
      - name: loans
        image: nazjara/loans:1.0.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_CONFIG_SERVER_URI
          value: http://config-server:8071
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: DB_URL
          value: jdbc:mysql://mysql-loans:3306/loansdb
        - name: SPRING_EUREKA_SERVER_URI
          value: http://discovery-service:8070
        - name: OTEL_SERVICE_NAME
          value: loans
        volumeMounts:
        - name: loans-persistent-storage
          mountPath: /app/data
      volumes:
      - name: loans-persistent-storage
        persistentVolumeClaim:
          claimName: loans-pvc
