apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cards-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards
spec:
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
      - name: cards
        image: nazjara/cards:1.0.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_CONFIG_SERVER_URI
          value: http://config-server:8071
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: DB_URL
          value: jdbc:mysql://mysql-cards:3306/cardsdb
        - name: SPRING_EUREKA_SERVER_URI
          value: http://discovery-service:8070
        - name: OTEL_SERVICE_NAME
          value: cards
        volumeMounts:
        - name: cards-persistent-storage
          mountPath: /app/data
      volumes:
      - name: cards-persistent-storage
        persistentVolumeClaim:
          claimName: cards-pvc
