apiVersion: v1
kind: Service
metadata:
  name: message
spec:
  selector:
    app: message
  ports:
    - port: 8095
      targetPort: 8095
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
spec:
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message
        image: nazjara/message:1.0.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8095
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        volumeMounts:
        - name: message-persistent-storage
          mountPath: /app/data
      volumes:
      - name: message-persistent-storage
        persistentVolumeClaim:
          claimName: message-pvc
