apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8072
      targetPort: 8072
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: nazjara/gateway-service:1.0.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 8072
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: SPRING_CONFIG_SERVER_URI
          value: http://config-server:8071
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_EUREKA_SERVER_URI
          value: http://discovery-service:8070
        - name: SPRING_REDIS_HOST
          value: redis
        - name: OTEL_SERVICE_NAME
          value: gateway-service
        - name: SPRING_OAUTH2_JWK_SET_URI
          value: http://keycloak:8080/realms/master/protocol/openid-connect/certs
        volumeMounts:
        - name: gateway-service-persistent-storage
          mountPath: /app/data
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8072
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8072
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: gateway-service-persistent-storage
        persistentVolumeClaim:
          claimName: gateway-service-pvc
