apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - port: 3200
      targetPort: 3200
      name: tempo
    - port: 4318
      targetPort: 4318
      name: otlp-http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.4.1
        args:
        - -config.file=/etc/tempo/tempo.yml
        ports:
        - containerPort: 3200
        - containerPort: 4318
          name: otlp-http
        volumeMounts:
        - name: tempo-persistent-storage
          mountPath: /var/tempo
        - name: tempo-config
          mountPath: /etc/tempo
      volumes:
      - name: tempo-persistent-storage
        persistentVolumeClaim:
          claimName: tempo-pvc
      - name: tempo-config
        configMap:
          name: tempo-config
